### ISSUE TITLE
Delete the duplicate class 

### ISSUE THREAD

**Issue by defo-cris** [defo-cris/progetto-programmazione-ad-oggetti-java#2]
Delete the duplicate class, and add a new class for the issue of the line 107 (issue #1).

**Comment by simone-viozzi** [comment]
we need to remove the class NewBufferedReader and make a new class that wrap the BufferedReader.
in the new class we will need a method that emulate the readLine() using read() and manually detect the end of the line (marked with a specific character). 
the new class/method need to cache all the character that exceed the current end of the line and store them until the next readline il called.
