### ISSUE TITLE
requested feature

### ISSUE THREAD

**Issue by simone-viozzi** [defo-cris/progetto-programmazione-ad-oggetti-java#3]
management of the import errors(number of element in a row, ..);
management in the request phase (request of an inesistent data, ...);

**Comment by simone-viozzi** [comment]
How much error handling have we already done?
if a row have less element what happen right now? (i think this should be related with the issue #2  ).

**Comment by defo-cris** [comment]
in theory in the our csv file we don't have row with less element

**Comment by simone-viozzi** [comment]
we need a revision on the error made when spring get a bad request
